baseURL = 'https://cruzio.dev/'
languageCode = 'en-us'
theme = 'PaperMod'
title = 'cruzio dev blog'
googleAnalytics = 'G-SM0LMV5REC'

[params]
env = "production"
title = "Cruzio Dev Blog"
description = "cruzio journal of development"
keywords = [ "cruzio", "machine learning", "development", "programming", "golang", "python", "serverless" ]
author = "Me"
DateFormat = "January 2, 2006"
ShowReadingTime = true
ShowShareButtons = true
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = false
ShowWordCount = true
ShowRssButtonInSectionTermList = true
UseHugoToc = true
disableSpecial1stPost = false
disableScrollToTop = false
comments = false
hidemeta = false
hideSummary = false
showtoc = false
tocopen = false

[params.assets]
favicon = "<link / abs url>"
favicon16x16 = "<link / abs url>"
favicon32x32 = "<link / abs url>"
apple_touch_icon = "<link / abs url>"
safari_pinned_tab = "<link / abs url>"

[params.label]
text = "Home"
icon = "/apple-touch-icon.png"
iconHeight = 35

[params.profileMode]
enabled = false
title = "Cruzio Dev"
subtitle = "my development journal that I somewhat update"
imageUrl = "https://avatars.githubusercontent.com/u/1786573?v=4"

[params.homeInfoParams]
Title = "Hi there 👋"
Content = "my development journal that I somewhat update"

[[params.socialIcons]]
name = "linkedin"
url = "https://www.linkedin.com/in/diogo-cruz-959182185/"

[[params.socialIcons]]
name = "github"
url = "https://github.com/dc-dc-dc"